# Generated by Django 3.2 on 2021-05-03 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ips', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ip',
            old_name='ip',
            new_name='ip_address',
        ),
    ]
